platform :ios, '8.0'
inhibit_all_warnings!

target 'BaiMapEagleEye' do

pod 'AFNetworking'
pod 'PureLayout'
pod 'FLEX'
pod 'NYXImagesKit'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'uicontrol-blocks'
#pod 'INTULocationManager'
pod 'YYKit'
pod 'MLeaksFinder'
pod 'BaiduMapKit'

end
